### ISSUE TITLE
Archive grass6 directory

### ISSUE THREAD

**Issue by NikosAlexandris** [OSGeo/grass-addons#257]
Is `grass6` still required to be in the master branch?  Could it be just archived?

**Comment by neteler** [comment]
No strong opinion - do you have a suggestion how to archive it best?

**Comment by wenzeslaus** [comment]
Well, technically, a `git rm` would be sufficient, but perhaps creating a dedicated, but a dead branch is better. That probably depends on what we want to do from here with the active code. Branch for each major release sounds reasonable, although it is just addressing the current issue rather than addressing the deeper problem of versioning addons and also matching them with supported versions. Anyway, something like:

```
git checkout -b grass6
git rm grass6
git mv grass7 src
```

...and around release of 8.0: `git checkout -b grass7`.

I would be interested in analysis of what modules were not ported from 6 to 7.

**Comment by ninsbl** [comment]
There is a _grass6_ branch now:
https://github.com/OSGeo/grass-addons/tree/grass6

I assume this can be closed?
An analysis which addons have not been ported to GRASS GIS 7/8 is probably a different issue...?

**Comment by wenzeslaus** [comment]
...and the master may need to be deleted to avoid confusion. (The other branches are based based on the master branch, so we should not loose any info. At least the last commit on master, 702671d53d62023397d35aab4f2b61b9b81660db, seems to be on grass8.)

**Comment by wenzeslaus** [comment]
Mostly resolved by #528. Remaining cleanup tracked in #1098. Closing.
