### ISSUE TITLE
[Bug] g.proj.identify does not install properly

### ISSUE THREAD

**Issue by baharmon** [OSGeo/grass-addons#302]
**Name of the addon**
g.proj.identify

**Describe the bug**
`g.proj.identify` does not install properly

**To Reproduce**
1. Run `g.proj.identify`
4. See error:
```
g.extension extension=g.proj.identify                                           
WARNING: Extension <g.proj.identify> already installed. Re-installing...
Downloading precompiled GRASS Addons <g.proj.identify>...
Updating addons metadata file...
Updating private addons metadata file...
WARNING: No addons metadata available. Addons metadata file not updated.
ERROR: Unable to read manual page: [Errno 2] No such file or directory: 'C:\\Users\\baharmon\\AppData\\Roaming\\GRASS7\\addons\\docs\\html\\g.proj.identify.html'
(Fri Oct  2 11:53:34 2020) Command finished (2 sec)                             
```

**Expected behavior**
Add-on module installs.

**System description:**
 - Operating System: Windows 10
- version=7.8.3
- date=2020
- revision=8bcecc9a6
- build_date=2020-05-05
- build_platform=x86_64-w64-mingw32
- build_off_t_size=8
- libgis_revision=8bcecc9a6
- libgis_date=2020-05-05T08:51:50+00:00
- proj=6.3.2
- gdal=3.0.4
- geos=3.8.1
- sqlite=3.29.0

**Comment by tmszi** [comment]
According  [list](http://wingrass.fsv.cvut.cz/grass78/x86_64/addons/latest/logs/) of precompiled GRASS GIS addons, there is an [error during importing the osgeo module](http://wingrass.fsv.cvut.cz/grass78/x86_64/addons/latest/logs/g.proj.identify.log) (python-gdal lib is missing). This is interesting because osgeo python lib (this is work in GRASS GIS Python shell: `from osgeo import osr`) is part of the installation of the GRASS GIS version for MS Windows. 

Maybe @landam could tell me how compiling addons works on a http://wingrass.fsv.cvut.cz server (and why gdal python lib is missing during compilation), please?

**Comment by neteler** [comment]
Could this import
https://github.com/OSGeo/grass-addons/blob/648817dad66bcb442b7eaf1a27d804c7999c897f/grass7/general/g.proj.identify/g.proj.identify.py#L58

be moved down to become lazy import?
