### ISSUE TITLE
[Bug] g.citation: Citation fails for all modules

### ISSUE THREAD

**Issue by ninsbl** [OSGeo/grass-addons#489]
**g.citation**

**Describe the bug**
g.citation fails for all modules with with the error message:
```The text does not contain date entry```

**To Reproduce**
```
g.extension extension=g.citation
g.citation -as
```

**Expected behavior**
g.citation should be able to provide citation for at least some modules...

**System description (please complete the following information):**
 - Ubuntu 18.04
 - GRASS GIS 7.8.5

**Comment by neteler** [comment]
The problem is here:

in #64 the SVN based "Date" tag was comment out since it no longer functions after the move to git(hub):

https://github.com/OSGeo/grass-addons/blob/619f9f9acf88149598fb50cbc0daaf9d5d3741a8/grass7/general/g.citation/g.citation.py#L189

Hence it fails.

"Easy" workaround: Replace the date check with `Retrieved: <current date>`

**Comment by ninsbl** [comment]
Fixed in #808
