### ISSUE TITLE
No metadata available when installing #r.area.createweight Add-On for GRASS GIS on Windows

### ISSUE THREAD

**Issue by naufalianf** [OSGeo/grass-addons#739]
Hello,
Currently im struggling when installing #r.area.createweight add on for my GRASS GIS, error always appear as down below in GRASS GIS 7.8.3, 7.8.7, 8.0.1. Im running on Windows 10 anyway

Please, i really need your advice, if there any solution for this

Error:

WARNING: No metadata available for module 'r.area.createweight': Unable to
fetch interface description for command '<r.area.createweight>'.

     Details: <Cannot find the executable r.area.createweight>
ERROR: Unable to read manual page: [Errno 2] No such file or directory:
'C:\Users\*in\AppData\Roaming\GRASS8\addons\docs\html\r.area.createweight.html'

![errorGRASS](https://user-images.githubusercontent.com/90570415/165057940-2e937031-ea25-4359-96c2-276c356b6eeb.PNG)

**Comment by tgrippa** [comment]
Hi @naufalianf  and thank you for reporting. 
I received a message from someone else last week with the same issue you are facing right now. 
I my side, I'm on Ubuntu 20.04 and GRASS 7.8.6 and I can (re-)install without any problem as you can see bellow. So, I'm guessing the problem is only with Windows. Maybe another Linux user can confirm ? 

> Mon Apr 25 10:56:12 2022)                                                      
g.extension r.area.createweight                                                 
WARNING: Extension <r.area.createweight> already installed. Re-installing...
Fetching <r.area.createweight> from GRASS GIS Addons repository (be patient)...
Compiling...
Installing...
Updating extensions metadata file...
Updating extension modules metadata file...
Installation of <r.area.createweight> successfully finished
(Mon Apr 25 10:56:25 2022) La commande s'est terminée (12 sec)                  
(Mon Apr 25 10:56:27 2022)                                                      
g.extension r.area.createweight operation=remove -f                             
Updating addons metadata file...
Extension <r.area.createweight> successfully uninstalled.
(Mon Apr 25 10:56:28 2022) La commande s'est terminée (0 sec)                   
(Mon Apr 25 10:56:35 2022)                                                      
g.extension r.area.createweight                                                 
Fetching <r.area.createweight> from GRASS GIS Addons repository (be patient)...
Compiling...
Installing...
Updating extensions metadata file...
Updating extension modules metadata file...
Installation of <r.area.createweight> successfully finished
(Mon Apr 25 10:56:44 2022) La commande s'est terminée (9 sec)

**Comment by neteler** [comment]
> Currently im struggling when installing #r.area.createweight add on for my GRASS GIS, error always appear as down below in GRASS GIS 7.8.3, 7.8.7, 8.0.1. Im running on Windows 10 anyway

You can check this here:
G7 addons:
https://wingrass.fsv.cvut.cz/grass78/x86_64/addons/grass-7.8.7dev/logs/
--> raster/r.area.createweight | FAILED
---> ERROR: Pandas is not installed

G8 addons:
https://wingrass.fsv.cvut.cz/grass80/x86_64/addons/grass-8.0.1/logs/
--> raster/r.area.createweight | FAILED
----> ERROR: Pandas is not installed

@landam Could you please install the Pandas package on the Windows server?

**Comment by naufalianf** [comment]
> > Currently im struggling when installing #r.area.createweight add on for my GRASS GIS, error always appear as down below in GRASS GIS 7.8.3, 7.8.7, 8.0.1. Im running on Windows 10 anyway
> 
> You can check this here: G7 addons: https://wingrass.fsv.cvut.cz/grass78/x86_64/addons/grass-7.8.7dev/logs/ --> raster/r.area.createweight | FAILED ---> ERROR: Pandas is not installed
> 
> G8 addons: https://wingrass.fsv.cvut.cz/grass80/x86_64/addons/grass-8.0.1/logs/ --> raster/r.area.createweight | FAILED ----> ERROR: Pandas is not installed
> 
> @landam Could you please install the Pandas package on the Windows server?

Helllo, thank you for responding my issue

That exactly error that appear

But apparently the issue is still there when im installing in ubuntu too

Did the Pandas package already added on the windows server yet?

**Comment by veroandreo** [comment]
Do you have pandas installed in Ubuntu? 

Note that when you install an addon in Windows it comes as a precompiled binary, but this is not the case for Linux, AFAIU. Hence, in Linux, you need to install dependencies. In any case, the addon should install even if pandas is not present and only yield error when trying to run it, i.e., dependencies should be lazy imported.

**Comment by naufalianf** [comment]
> Do you have pandas installed in Ubuntu?
> 
> Note that when you install an addon in Windows it comes as a precompiled binary, but this is not the case for Linux, AFAIU. Hence, in Linux, you need to install dependencies. In any case, the addon should install even if pandas is not present and only yield error when trying to run it, i.e., dependencies should be lazy imported.

Thanks for the enlightenment, and it's definitely true that dependencies are the key on Ubuntu. So glad I finally managed to do the install though I still wish I could run it on Windows.

Thanks all for the support!
