### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by plvoit** [OSGeo/grass-addons#763]
**Name of the addon**
r.stream.distance and others

**Describe the bug**
Addons such as r.stream.distance can not be installed by GUI, or terminal (g.extension r.stream.distance). The link to the repo seems to be wrong (the link contains "trunk" while it should possibly be "tree"):
"svn: E170000: URL 'https://github.com/OSGeo/grass-
addons/trunk/grass7/raster/r.stream.distance' doesn't exist

**To Reproduce**
1. GUI: Settings > Addons extensions > Instal extensions from addons > raster > r.stream.distance > Error

**Expected behavior**
g.extension should be able to download and install the extension.

**System description (please complete the following information):**
 - Ubuntu 20.04.3 LTS
 - GRASS GIS 7.8.2 64-bit

**Comment by neteler** [comment]
Please updated your GRASS GIS installation:  version [7.8.2](https://trac.osgeo.org/grass/wiki/Release/7.8.2-News) is from 11 Dec 2019. Since then the addon repository structure has been modernised, precisely on Jun 28, 2021 (#571).

To be able to install addons you need at least GRASS GIS [7.8.6](https://trac.osgeo.org/grass/wiki/Release/7.8.6-News#Majormodulechanges).

Of course we highly recommend GRASS GIS [8.2](https://github.com/OSGeo/grass/releases/tag/8.2.0) or any later future version ;-)

**Comment by plvoit** [comment]
Thank you for the quick reply. Now it works
