### ISSUE TITLE
[Bug] Addon manuals don`t build in CI

### ISSUE THREAD

**Issue by ninsbl** [OSGeo/grass-addons#803]
**all addons**
During github workflows, it seems that manuals are not build:
https://github.com/OSGeo/grass-addons/actions/runs/3172752971/jobs/5167576298#step:13:41

**Describe the bug**
During build of addons in CI the following error message pops up:
`FileNotFoundError: [Errno 2] No such file or directory: '/home/runner/install/grass*'`

**To Reproduce**
See: https://github.com/OSGeo/grass-addons/actions/runs/3172752971/jobs/5167576298#step:13:41

**Expected behavior**
Addon manuals should build in CI

**System description (please complete the following information):**
- Operating System: Ubuntu Linux
- GRASS GIS version 8.3.dev

**Comment by tmszi** [comment]
Problematic is using wildcard `*` inside  `MODULE_TOPDIR` ENV var because Python code `os.chdir()` doesn't  interpret this wildcard.

https://github.com/OSGeo/grass-addons/actions/runs/3172752971/jobs/5167576298#step:13:4

```shell
GRASS_INSTALL=$HOME/install/grass*
make MODULE_TOPDIR=$GRASS_INSTALL
```

Get ENV var `MODULE_TOPDIR` (inside mkhtml.py):

https://github.com/OSGeo/grass/blob/main/utils/mkhtml.py#L724

Change dir to `MODULE_TOPDIR` doesn't work, because dir `/home/runner/install/grass*` doesn't exists:

https://github.com/OSGeo/grass/blob/main/utils/mkhtml.py#L309
